#!/usr/bin/env python3
from __future__ import annotations

import csv
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "release_manifest.json"
TABLE_SPEC = ROOT / "configs" / "machine_readable_tables.json"
TABLE_DIR = ROOT / "supplementary" / "machine_readable"
EVALUATION_REGISTRY = ROOT / "configs" / "evaluations.json"
CORE_PARITY = ROOT / "results" / "verified_manifests" / "core_module_parity.json"
DESCRIPTOR_PROTOCOLS = ROOT / "configs" / "descriptor_protocols.json"
DESCRIPTOR_PARITY = ROOT / "results" / "verified_manifests" / "descriptor_branch_parity.json"
DESCRIPTOR_CLEAN_SMOKE = ROOT / "results" / "verified_manifests" / "descriptor_clean_environment_smoke.json"
TRAINING_PARITY = ROOT / "results" / "verified_manifests" / "training_orchestration_parity.json"
TRAINING_CLEAN_SMOKE = ROOT / "results" / "verified_manifests" / "training_orchestration_clean_environment_smoke.json"
LANGUAGE_VARIANTS = ROOT / "configs" / "chemberta_variants.json"
LANGUAGE_PARITY = ROOT / "results" / "verified_manifests" / "language_branch_parity.json"
LANGUAGE_CLEAN_SMOKE = ROOT / "results" / "verified_manifests" / "language_clean_environment_smoke.json"
GEOMETRY_CONFIG = ROOT / "configs" / "geometry_branch.json"
GEOMETRY_PARITY = ROOT / "results" / "verified_manifests" / "geometry_branch_parity.json"
GEOMETRY_CLEAN_SMOKE = ROOT / "results" / "verified_manifests" / "geometry_clean_environment_smoke.json"
FUSION_CONFIG = ROOT / "configs" / "fusion_ensemble.json"
FUSION_PARITY = ROOT / "results" / "verified_manifests" / "fusion_branch_parity.json"
FUSION_CLEAN_SMOKE = ROOT / "results" / "verified_manifests" / "fusion_clean_environment_smoke.json"
ADAPTER_CONFIG = ROOT / "configs" / "dataset_adapters.json"
ADAPTER_PARITY = ROOT / "results" / "verified_manifests" / "dataset_adapter_parity.json"
ADAPTER_CLEAN_SMOKE = ROOT / "results" / "verified_manifests" / "dataset_adapter_clean_environment_smoke.json"
DATA_ACQUISITION = ROOT / "configs" / "data_acquisition.json"
EVALUATION_RUNNER_PARITY = ROOT / "results" / "verified_manifests" / "evaluation_runner_parity.json"
EVALUATION_RUNNER_CLEAN_SMOKE = ROOT / "results" / "verified_manifests" / "evaluation_runner_clean_environment_smoke.json"
LICENSE_FILE = ROOT / "LICENSE"

TEXT_SUFFIXES = {".cff", ".csv", ".json", ".md", ".py", ".txt", ".yaml", ".yml"}
TEXT_DOTFILES = {".gitattributes", ".gitignore"}
INTERNAL_NAMES = ("code" + "x", "clau" + "de", "hand" + "off")
FORBIDDEN_PATTERNS = {
    "internal_agent_or_workflow_name": re.compile(
        r"\b(?:" + "|".join(INTERNAL_NAMES) + r")\b|"
        + "agent" + r"[_ -]?" + "work|"
        + "ai" + r"[- ]?(?:" + "generated|written|authored)|"
        + "written by " + "ai|generated by " + "ai",
        re.IGNORECASE,
    ),
    "private_absolute_path": re.compile(r"/(?:data|home)/koo/", re.IGNORECASE),
    "cluster_identifier": re.compile(r"(?:fai00[0-9]|goo[0-9]{4,})", re.IGNORECASE),
    "credential_assignment": re.compile(
        r"(?:api[_-]?key|access[_-]?token|secret|password)\s*[:=]\s*['\"][^'\"]+",
        re.IGNORECASE,
    ),
}

EXPECTED_EVALUATIONS = {
    "R01": ("out_of_fold", 8047, 5),
    "R02": ("out_of_fold", 17937, 5),
    "R03": ("out_of_fold", 7985, 5),
    "R04": ("supplied_test", 1997, None),
    "R05": ("supplied_test", 980, None),
    "R09": ("supplied_test", 1282, None),
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_manifest(errors: list[str]) -> None:
    payload = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if payload.get("release_stage") != "V1_REPRODUCIBILITY_PACKAGE_DEVELOPMENT":
        errors.append("release stage does not match the selected v1.0 reproducibility scope")
    for relative, expected in payload["files"].items():
        path = ROOT / relative
        if not path.is_file():
            errors.append(f"missing manifest file: {relative}")
            continue
        if path.stat().st_size != expected["bytes"]:
            errors.append(f"byte-size mismatch: {relative}")
        if sha256(path) != expected["sha256"]:
            errors.append(f"sha256 mismatch: {relative}")


def validate_release_policy(errors: list[str]) -> None:
    text = LICENSE_FILE.read_text(encoding="utf-8") if LICENSE_FILE.is_file() else ""
    if not text.startswith("MIT License\n"):
        errors.append("MIT licence file is missing or malformed")
    if "Copyright (c) 2026 Hyunmo Goo and Hyeongwoo Kong" not in text:
        errors.append("MIT copyright attribution is missing")


def validate_tables(errors: list[str]) -> None:
    specs = json.loads(TABLE_SPEC.read_text(encoding="utf-8"))["tables"]
    actual_names = {path.name for path in TABLE_DIR.glob("*.csv")}
    if actual_names != set(specs):
        errors.append("machine-readable CSV set differs from the declared table specification")
    for name, expected in specs.items():
        path = TABLE_DIR / name
        if not path.is_file():
            continue
        with path.open(newline="", encoding="utf-8-sig") as handle:
            reader = csv.reader(handle)
            try:
                header = next(reader)
            except StopIteration:
                errors.append(f"empty CSV: {name}")
                continue
            rows = sum(1 for _ in reader)
        if len(header) != expected["columns"]:
            errors.append(f"column-count mismatch: {name}")
        if rows != expected["rows"]:
            errors.append(f"row-count mismatch: {name}")


def validate_evaluation_registry(errors: list[str]) -> None:
    payload = json.loads(EVALUATION_REGISTRY.read_text(encoding="utf-8"))
    if payload.get("schema_version") != 1:
        errors.append("unsupported evaluation-registry schema")
    firewall = payload.get("common_label_firewall", {})
    if firewall.get("scored_labels_allowed_for") != ["scoring"]:
        errors.append("evaluation registry weakens the scored-label firewall")
    records = payload.get("evaluations", [])
    observed = {record.get("evaluation_id"): record for record in records}
    if set(observed) != set(EXPECTED_EVALUATIONS):
        errors.append("evaluation registry does not contain the exact primary evaluation set")
        return
    for evaluation_id, expected in EXPECTED_EVALUATIONS.items():
        record = observed[evaluation_id]
        actual = (record.get("design"), record.get("expected_rows"), record.get("outer_folds"))
        if actual != expected:
            errors.append(f"evaluation-registry mismatch: {evaluation_id}")
    expected_aggregation = {
        "R01": "one held-out prediction per outer fold",
        "R02": "one held-out prediction per outer fold",
        "R03": "one held-out prediction per outer fold",
        "R04": "mean of five split-model predictions per supplied-test row",
        "R05": "mean of five split-model predictions per supplied-test row",
        "R09": "one prediction per supplied-test row",
    }
    for evaluation_id, aggregation in expected_aggregation.items():
        if observed[evaluation_id].get("prediction_aggregation") != aggregation:
            errors.append(f"evaluation aggregation mismatch: {evaluation_id}")


def validate_core_parity(errors: list[str]) -> None:
    payload = json.loads(CORE_PARITY.read_text(encoding="utf-8"))
    records = payload.get("evaluations", [])
    if payload.get("status") != "PASS":
        errors.append("canonical core parity status is not PASS")
    if {record.get("evaluation_id") for record in records} != set(EXPECTED_EVALUATIONS):
        errors.append("canonical core parity does not cover all primary evaluations")
    if sum(record.get("rows", 0) for record in records) != sum(item[1] for item in EXPECTED_EVALUATIONS.values()):
        errors.append("canonical core parity row total mismatch")
    if payload.get("max_metric_absolute_difference") != 0.0:
        errors.append("canonical metric parity mismatch")
    if payload.get("max_bootstrap_absolute_difference") != 0.0:
        errors.append("canonical paired-bootstrap parity mismatch")
    if payload.get("max_blend_reconstruction_absolute_difference", float("inf")) > 2e-7:
        errors.append("canonical fixed-blend reconstruction exceeds tolerance")


def validate_descriptor_branch(errors: list[str]) -> None:
    protocols = json.loads(DESCRIPTOR_PROTOCOLS.read_text(encoding="utf-8"))
    if protocols.get("schema_version") != 1:
        errors.append("unsupported descriptor-protocol schema")
        return
    records = protocols.get("protocols", {})
    expected_counts = {
        "aqsoldbc": [373, 353, 354, 352, 356],
        "tdc": [337, 341, 337, 340, 338],
        "complat": [646, 650, 654, 650, 650],
        "jchem": [571, 575, 572, 574, 615],
    }
    if set(records) != set(expected_counts):
        errors.append("descriptor protocol set is incomplete")
        return
    for name, expected in expected_counts.items():
        key = "expected_split_feature_counts" if name == "jchem" else "expected_outer_feature_counts"
        if records[name].get(key) != expected:
            errors.append(f"descriptor feature-count contract mismatch: {name}")
    rules = {
        "aqsoldbc": (0, 0.95, "gt"),
        "tdc": (1, 0.98, "ge"),
        "complat": (1, None, None),
        "jchem": (1, 0.98, "ge"),
    }
    for name, expected in rules.items():
        filtering = records[name]["filtering"]
        actual = (
            filtering.get("variance_ddof"),
            filtering.get("correlation_threshold"),
            filtering.get("correlation_comparison"),
        )
        if actual != expected:
            errors.append(f"descriptor filtering contract mismatch: {name}")
    parity = json.loads(DESCRIPTOR_PARITY.read_text(encoding="utf-8"))
    if parity.get("status") != "PASS":
        errors.append("descriptor branch parity status is not PASS")
    if parity.get("row_level_inputs_redistributed") is not False:
        errors.append("descriptor parity manifest misstates row-level redistribution")
    if set(parity.get("protocols", {})) != set(expected_counts):
        errors.append("descriptor parity does not cover every protocol")
        return
    for name, expected in expected_counts.items():
        record = parity["protocols"][name]
        if record.get("retained_feature_counts") != expected:
            errors.append(f"descriptor parity feature-count mismatch: {name}")
        if record.get("feature_schema_parity") is not True or record.get("candidate_parity") is not True:
            errors.append(f"descriptor parity check failed: {name}")
    if parity.get("synthetic_xgboost_constructor_max_absolute_prediction_difference") != 0.0:
        errors.append("descriptor XGBoost constructor parity mismatch")
    smoke = json.loads(DESCRIPTOR_CLEAN_SMOKE.read_text(encoding="utf-8"))
    if smoke.get("status") != "PASS" or smoke.get("tests_discovered") != 16:
        errors.append("descriptor clean-environment smoke test failed")
    if smoke.get("failures") != 0 or smoke.get("errors") != 0:
        errors.append("descriptor clean-environment tests were not clean")
    if smoke.get("mordred_descriptor_columns") != 1613:
        errors.append("descriptor clean-environment Mordred contract mismatch")


def validate_training_orchestration(errors: list[str]) -> None:
    parity = json.loads(TRAINING_PARITY.read_text(encoding="utf-8"))
    expected = {
        "aqsoldbc_selected_trials": [4, 8, 4, 0, 0],
        "aqsoldbc_final_tree_counts": [3456, 3332, 3064, 2601, 3198],
        "tdc_selected_trials": [7, 19, 5, 0, 7],
        "tdc_best_iterations": [230, 377, 650, 365, 955],
        "complat_selected_trial": 2,
        "jchem_selected_trials": [3, 15, 6, 6, 11],
    }
    if parity.get("status") != "PASS" or parity.get("gate") != "training_orchestration_o1":
        errors.append("training orchestration parity status is not PASS")
    if parity.get("row_level_inputs_redistributed") is not False:
        errors.append("training orchestration manifest misstates row-level redistribution")
    if parity.get("observed") != expected or parity.get("expected") != expected:
        errors.append("training orchestration historical selection parity mismatch")
    smoke = json.loads(TRAINING_CLEAN_SMOKE.read_text(encoding="utf-8"))
    if smoke.get("status") != "PASS" or smoke.get("tests_discovered") != 28:
        errors.append("training orchestration clean-environment smoke test failed")
    if smoke.get("failures") != 0 or smoke.get("errors") != 0:
        errors.append("training orchestration clean-environment tests were not clean")


def validate_language_branch(errors: list[str]) -> None:
    variants = json.loads(LANGUAGE_VARIANTS.read_text(encoding="utf-8"))
    if variants.get("schema_version") != 2:
        errors.append("unsupported ChemBERTa variant schema")
        return
    expected_scope = {
        "randomized_single_task": "final_dlg_sol_language_encoder",
        "canonical_multitask": "development_candidate_not_final_dlg_sol",
        "canonical_single_task": "development_candidate_not_final_dlg_sol",
    }
    if variants.get("final_model_profile") != "randomized_single_task" or variants.get("variant_scope") != expected_scope:
        errors.append("ChemBERTa final and development scopes are misstated")
    model = variants.get("pretrained_model", {})
    if model.get("identifier") != "seyonec/ChemBERTa-zinc-base-v1":
        errors.append("ChemBERTa pretrained identifier mismatch")
    if model.get("revision") is not None or model.get("revision_status") != "not_recorded_in_historical_run":
        errors.append("ChemBERTa revision provenance is misstated")
    records = variants.get("variants", {})
    expected = {
        "canonical_multitask": (5e-5, 0, "logS_plus_auxiliary", 0.15),
        "randomized_single_task": (2e-5, 2, "logS", 0.0),
        "canonical_single_task": (5e-5, 0, "logS", 0.0),
    }
    if set(records) != set(expected):
        errors.append("ChemBERTa variant set is incomplete")
        return
    for name, values in expected.items():
        record = records[name]
        observed = (
            record.get("learning_rate"),
            record.get("training_randomized_smiles_per_molecule"),
            record.get("task"),
            record.get("auxiliary_weight"),
        )
        if observed != values:
            errors.append(f"ChemBERTa variant contract mismatch: {name}")
    if records["canonical_multitask"].get("auxiliary_targets") != ["logp", "tpsa", "molwt", "hbd", "hba"]:
        errors.append("ChemBERTa auxiliary-target contract mismatch")
    parity = json.loads(LANGUAGE_PARITY.read_text(encoding="utf-8"))
    if parity.get("status") != "PASS" or parity.get("gate") != "chemberta_language_l1":
        errors.append("ChemBERTa language parity status is not PASS")
    if parity.get("row_level_inputs_redistributed") is not False or parity.get("checkpoints_redistributed") is not False or parity.get("embeddings_redistributed") is not False:
        errors.append("ChemBERTa parity manifest misstates redistribution")
    if parity.get("pretrained_revision_recorded") is not False or parity.get("configuration_parity") is not True:
        errors.append("ChemBERTa configuration provenance mismatch")
    auxiliary = parity.get("auxiliary_target_parity", {})
    if auxiliary.get("rows") != 10298 or auxiliary.get("columns") != ["logp", "tpsa", "molwt", "hbd", "hba"]:
        errors.append("ChemBERTa auxiliary-target parity shape mismatch")
    if parity.get("auxiliary_absolute_tolerance") != 1e-12 or parity.get("embedding_absolute_tolerance") != 3e-6:
        errors.append("ChemBERTa parity tolerance contract mismatch")
    if auxiliary.get("archived_missing_values") != 0 or auxiliary.get("recomputed_missing_values") != 0 or auxiliary.get("maximum_absolute_difference", float("inf")) > 1e-12:
        errors.append("ChemBERTa auxiliary-target parity mismatch")
    embeddings = parity.get("embedding_extraction_parity", [])
    if {record.get("variant") for record in embeddings} != set(expected):
        errors.append("ChemBERTa embedding parity does not cover every variant")
    for record in embeddings:
        if record.get("archived_embedding_shape") != [10298, 768] or record.get("observed_embedding_shape") != [16, 768]:
            errors.append("ChemBERTa embedding shape mismatch")
        if record.get("maximum_absolute_difference", float("inf")) > 3e-6 or record.get("finite") is not True:
            errors.append("ChemBERTa embedding extraction parity mismatch")
    smoke = json.loads(LANGUAGE_CLEAN_SMOKE.read_text(encoding="utf-8"))
    if smoke.get("status") != "PASS" or smoke.get("tests_discovered") != 37:
        errors.append("ChemBERTa clean-environment smoke test failed")
    if smoke.get("failures") != 0 or smoke.get("errors") != 0 or smoke.get("skipped") != 0:
        errors.append("ChemBERTa clean-environment tests were not clean")


def validate_geometry_branch(errors: list[str]) -> None:
    config = json.loads(GEOMETRY_CONFIG.read_text(encoding="utf-8"))
    if config.get("schema_version") != 1:
        errors.append("unsupported geometry configuration schema")
        return
    graph = config.get("graph_construction", {})
    model = config.get("model", {})
    dimensions = (graph.get("node_dimension"), graph.get("edge_dimension"), graph.get("auxiliary_dimension"))
    if dimensions != (42, 24, 19):
        errors.append("geometry feature-dimension contract mismatch")
    graph_contract = (
        graph.get("conformers_attempted"),
        graph.get("conformers_retained"),
        graph.get("proximity_cutoff_angstrom"),
        graph.get("explicit_hydrogen_policy"),
    )
    if graph_contract != (5, 3, 4.5, "hydrogens_bonded_to_nitrogen_or_oxygen"):
        errors.append("geometry graph-construction contract mismatch")
    if model.get("architecture") != "distance_aware_scalar_3d_mpnn" or model.get("coordinate_updates") is not False:
        errors.append("geometry model architecture is misstated")
    if model.get("checkpoint_selection") != "selection_rmse":
        errors.append("geometry checkpoint-selection contract mismatch")
    parity = json.loads(GEOMETRY_PARITY.read_text(encoding="utf-8"))
    if parity.get("status") != "PASS" or parity.get("gate") != "geometry_branch_g1":
        errors.append("geometry branch parity status is not PASS")
    redistribution = (
        parity.get("row_level_inputs_redistributed"),
        parity.get("conformer_caches_redistributed"),
        parity.get("coordinates_redistributed"),
        parity.get("checkpoints_redistributed"),
        parity.get("embeddings_redistributed"),
    )
    if redistribution != (False, False, False, False, False):
        errors.append("geometry parity manifest misstates redistribution")
    cache = parity.get("development_cache", {})
    if (cache.get("records"), cache.get("graphs")) != (10298, 24457):
        errors.append("geometry development-cache shape mismatch")
    probe = parity.get("graph_reconstruction_probe", {})
    if (probe.get("rows"), probe.get("graphs")) != (16, 36):
        errors.append("geometry graph-reconstruction probe shape mismatch")
    if probe.get("record_graph_counts_equal") is not True or probe.get("edge_indices_equal") is not True:
        errors.append("geometry graph-reconstruction topology mismatch")
    if any(value != 0.0 for value in probe.get("maximum_absolute_difference", {}).values()):
        errors.append("geometry graph-reconstruction value mismatch")
    checkpoints = parity.get("checkpoint_strict_loads", [])
    if len(checkpoints) != 5 or not all(record.get("strict_load") is True for record in checkpoints):
        errors.append("geometry archived-checkpoint strict-load coverage mismatch")
    embedding = parity.get("embedding_extraction_probe", {})
    if embedding.get("archived_embedding_shape") != [10298, 256] or embedding.get("rows") != 16:
        errors.append("geometry embedding parity shape mismatch")
    if embedding.get("absolute_tolerance") != 3e-6 or embedding.get("maximum_absolute_difference", float("inf")) > 3e-6:
        errors.append("geometry embedding parity mismatch")
    if embedding.get("embedding_plus_auxiliary_maximum_absolute_difference", float("inf")) > 3e-6 or embedding.get("finite") is not True:
        errors.append("geometry embedding-plus-auxiliary parity mismatch")
    prediction = parity.get("prediction_probe", {})
    if prediction.get("rows") != 16 or prediction.get("absolute_tolerance") != 3e-6 or prediction.get("maximum_absolute_difference", float("inf")) > 3e-6 or prediction.get("finite") is not True:
        errors.append("geometry prediction parity mismatch")
    if parity.get("coordinate_updates") is not False or parity.get("scored_inference_accepts_labels") is not False:
        errors.append("geometry architecture or label-firewall manifest mismatch")
    smoke = json.loads(GEOMETRY_CLEAN_SMOKE.read_text(encoding="utf-8"))
    if smoke.get("status") != "PASS" or smoke.get("tests_discovered") != 44 or smoke.get("geometry_tests") != 7:
        errors.append("geometry clean-environment smoke test failed")
    if smoke.get("failures") != 0 or smoke.get("errors") != 0 or smoke.get("skipped") != 0:
        errors.append("geometry clean-environment tests were not clean")
    if smoke.get("validator_counterexamples") != 2 or smoke.get("coordinate_update_misstatement_rejected") is not True or smoke.get("embedding_parity_mismatch_rejected") is not True:
        errors.append("geometry validator counterexamples were not recorded")


def validate_fusion_branch(errors: list[str]) -> None:
    config = json.loads(FUSION_CONFIG.read_text(encoding="utf-8"))
    if config.get("schema_version") != 2 or config.get("model_identity") != "aug2_head4":
        errors.append("unsupported fusion configuration schema")
        return
    expected = [
        (0, "randomized_single_task", "raw_standardized_concat", "residual_mlp", 260901, 29),
        (1, "randomized_single_task", "raw_standardized_concat", "residual_mlp", 260902, 82),
        (2, "randomized_single_task", "raw_standardized_concat", "residual_mlp", 260903, 40),
        (3, "randomized_single_task", "raw_standardized_concat", "residual_mlp", 260904, 21),
    ]
    observed = [
        (
            record.get("member_index"),
            record.get("language_variant"),
            record.get("preprocessing"),
            record.get("regressor"),
            record.get("base_seed"),
            record.get("fixed_epochs"),
        )
        for record in config.get("members", [])
    ]
    if observed != expected:
        errors.append("fusion-head mapping differs from the canonical aug2_head4 contract")
    preprocessing = config.get("preprocessing", {})
    if preprocessing.get("fit_partition_only") is not True or preprocessing.get("method") != "modality_wise_standardization_then_raw_concatenation":
        errors.append("fusion preprocessing contract mismatch")
    if preprocessing.get("pca_used_by_final_model") is not False or preprocessing.get("l2_normalization_used_by_final_model") is not False:
        errors.append("PCA or L2 normalization is incorrectly represented as final")
    if preprocessing.get("adapter_winsorization") != {"aqsoldbc": True, "complat": True, "tdc": True, "jchem": False}:
        errors.append("fusion adapter winsorization mapping mismatch")
    if preprocessing.get("failed_geometry_fallback_uses_labels") is not False:
        errors.append("fusion adapter or fallback boundary is misstated")
    architecture = config.get("head_architecture", {})
    if architecture != {"hidden": 384, "depth": 2, "dropout": 0.45, "output_dimension": 1}:
        errors.append("fusion residual-head architecture mismatch")
    training = config.get("training", {})
    expected_training = {
        "loss": "mean_squared_error",
        "optimizer": "AdamW",
        "learning_rate": 0.0005,
        "weight_decay": 0.0005,
        "batch_size": 128,
        "gradient_clip_norm": 5.0,
        "epoch_policy": "fixed_per_head",
        "fold_seed_rule": "base_seed_plus_100000_times_fold_index",
        "schedule_provenance": "per-seed median best epoch from AqSolDBc five-fold development",
    }
    if training != expected_training:
        errors.append("fusion fixed-head training policy mismatch")
    prediction = config.get("neural_prediction", {})
    if (
        prediction.get("aggregation"),
        prediction.get("expected_members"),
        prediction.get("shared_input_representation"),
        prediction.get("input_dependent_weights"),
    ) != ("arithmetic_mean", 4, True, False):
        errors.append("neural-member aggregation contract mismatch")
    parity = json.loads(FUSION_PARITY.read_text(encoding="utf-8"))
    if parity.get("status") != "PASS" or parity.get("gate") != "canonical_aug2_head4_identity_f2" or parity.get("model_identity") != "aug2_head4":
        errors.append("fusion branch parity status is not PASS")
    redistribution = (
        parity.get("row_level_inputs_redistributed"),
        parity.get("checkpoints_redistributed"),
        parity.get("embeddings_redistributed"),
        parity.get("predictions_redistributed"),
    )
    if redistribution != (False, False, False, False):
        errors.append("fusion parity manifest misstates redistribution")
    parity_mapping = [
        (
            record.get("member_index"),
            record.get("language_variant"),
            record.get("preprocessing"),
            record.get("regressor"),
            record.get("base_seed"),
            record.get("fixed_epochs"),
        )
        for record in parity.get("members", [])
    ]
    if parity_mapping != expected:
        errors.append("fusion parity head mapping mismatch")
    evaluations = {record.get("evaluation_id"): record for record in parity.get("evaluations", [])}
    expected_rows = {"R01": 8047, "R02": 17937, "R03": 7985, "R04": 1997, "R05": 980, "R09": 1282}
    if set(evaluations) != set(expected_rows):
        errors.append("fusion identity parity evaluation set mismatch")
    else:
        for evaluation_id, rows in expected_rows.items():
            record = evaluations[evaluation_id]
            if record.get("rows") != rows or record.get("record_id_unique_in_both_sources") is not True or record.get("record_id_coverage_complete") is not True:
                errors.append(f"fusion row identity coverage mismatch: {evaluation_id}")
            if record.get("maximum_absolute_prediction_difference") != 0.0:
                errors.append(f"fusion neural prediction identity mismatch: {evaluation_id}")
    if parity.get("all_six_evaluations_match") is not True or parity.get("maximum_absolute_prediction_difference") != 0.0:
        errors.append("fusion six-evaluation identity summary mismatch")
    if parity.get("scored_inference_accepts_labels") is not False:
        errors.append("fusion scored-inference label firewall is misstated")
    smoke = json.loads(FUSION_CLEAN_SMOKE.read_text(encoding="utf-8"))
    if smoke.get("status") != "PASS" or smoke.get("tests_discovered") < 55 or smoke.get("fusion_tests") < 11:
        errors.append("fusion clean-environment smoke test failed")
    if smoke.get("failures") != 0 or smoke.get("errors") != 0 or smoke.get("skipped") != 0:
        errors.append("fusion clean-environment tests were not clean")
    if smoke.get("validator_counterexamples", 0) < 3 or smoke.get("universal_winsorization_misstatement_rejected") is not True or smoke.get("incomplete_member_mapping_rejected") is not True or smoke.get("prediction_identity_mismatch_rejected") is not True:
        errors.append("fusion validator counterexamples were not recorded")


def validate_dataset_adapters(errors: list[str]) -> None:
    config = json.loads(ADAPTER_CONFIG.read_text(encoding="utf-8"))
    if config.get("schema_version") != 1 or config.get("model_identity") != "aug2_head4" or config.get("fold_seed_multiplier") != 100000:
        errors.append("unsupported dataset-adapter configuration")
        return
    output = config.get("common_output_schema", {})
    if output != {"record_key": "record_id", "fold_column": "fold_index", "member_columns": ["head_0", "head_1", "head_2", "head_3"], "canonical_neural_column": "aug2_head4"}:
        errors.append("dataset-adapter output schema mismatch")
    records = {record.get("evaluation_id"): record for record in config.get("evaluation_adapters", [])}
    expected = {
        "R01": ("aqsoldbc", "split", ["Train"], [], ["External"], ["Val"], [0, 1, 2, 3, 4], True, 0.001, "one_held_out_prediction", 8047, "prespecified_0.5", "aug2_head4"),
        "R02": ("complat", "split", ["Train"], [], ["External"], [], [0, 1, 2, 3, 4], True, 0.001, "one_held_out_prediction", 17937, "cross_fitted_from_training_side_oof", "aug2_head4"),
        "R03": ("tdc", "partition", ["fit"], [], ["oof_holdout"], ["selection", "official_test"], [0, 1, 2, 3, 4], True, 0.001, "one_held_out_prediction", 7985, "cross_fitted_from_training_side_oof", "aug2_head4"),
        "R04": ("tdc", "partition", ["fit"], [], ["official_test"], ["selection", "oof_holdout"], [0, 1, 2, 3, 4], True, 0.001, "mean_across_split_models", 1997, "one_coefficient_from_complete_tdc_oof", "aug2_head4"),
        "R05": ("jchem", "split", ["Train"], ["Val"], ["External"], [], [1, 2, 3, 4, 5], False, None, "mean_across_split_models", 980, "validation_only_within_each_reported_split", "aug2_head4"),
        "R09": ("complat", "split", ["Train"], [], ["External"], [], [0], True, 0.001, "single_full_refit", 1282, "one_coefficient_from_complete_complat_oof", "polarh_aug2_head4"),
    }
    if set(records) != set(expected):
        errors.append("dataset-adapter evaluation set mismatch")
    else:
        for evaluation_id, contract in expected.items():
            record = records[evaluation_id]
            observed = (
                record.get("dataset_id"), record.get("partition_column"), record.get("fit_values"), record.get("coefficient_values"), record.get("scored_values"), record.get("reserved_values"), record.get("fold_indices"), record.get("winsorization"), record.get("winsor_quantile"), record.get("scored_prediction_aggregation"), record.get("expected_scored_rows"), record.get("coefficient_policy"), record.get("historical_neural_column"),
            )
            if observed != contract:
                errors.append(f"dataset-adapter contract mismatch: {evaluation_id}")
    parity = json.loads(ADAPTER_PARITY.read_text(encoding="utf-8"))
    if parity.get("status") != "PASS" or parity.get("gate") != "dataset_specific_adapter_a1" or parity.get("model_identity") != "aug2_head4":
        errors.append("dataset-adapter parity status is not PASS")
    if (parity.get("row_level_inputs_redistributed"), parity.get("embeddings_redistributed"), parity.get("predictions_redistributed")) != (False, False, False):
        errors.append("dataset-adapter parity manifest misstates redistribution")
    role_checks = parity.get("role_checks", [])
    if len(role_checks) != 26 or {record.get("evaluation_id") for record in role_checks} != set(expected):
        errors.append("dataset-adapter role parity coverage mismatch")
    if any(any(value != 0 for value in record.get("role_mismatches", [])) for record in role_checks):
        errors.append("dataset-adapter partition-role parity mismatch")
    preprocessing = parity.get("preprocessing_checks", [])
    aggregation = parity.get("aggregation_checks", [])
    if {record.get("evaluation_id") for record in preprocessing} != set(expected) or {record.get("evaluation_id") for record in aggregation} != set(expected):
        errors.append("dataset-adapter preprocessing or aggregation coverage mismatch")
    if parity.get("maximum_role_mismatches") != 0 or parity.get("maximum_preprocessing_absolute_difference") != 0.0:
        errors.append("dataset-adapter historical implementation parity mismatch")
    if parity.get("maximum_aggregation_absolute_difference", float("inf")) > 2e-14:
        errors.append("dataset-adapter scored-prediction aggregation parity mismatch")
    if parity.get("scored_metadata_accepts_labels") is not False or parity.get("all_primary_evaluations_covered") is not True:
        errors.append("dataset-adapter label firewall or evaluation coverage is misstated")
    smoke = json.loads(ADAPTER_CLEAN_SMOKE.read_text(encoding="utf-8"))
    if smoke.get("status") != "PASS" or smoke.get("tests_discovered") != 65 or smoke.get("adapter_tests") != 10:
        errors.append("dataset-adapter clean-environment smoke test failed")
    if smoke.get("failures") != 0 or smoke.get("errors") != 0 or smoke.get("skipped") != 0:
        errors.append("dataset-adapter clean-environment tests were not clean")
    if smoke.get("validator_counterexamples") != 3 or smoke.get("jchem_winsorization_drift_rejected") is not True or smoke.get("tdc_fit_role_drift_rejected") is not True or smoke.get("aggregation_parity_mismatch_rejected") is not True:
        errors.append("dataset-adapter validator counterexamples were not recorded")


def validate_evaluation_runner(errors: list[str]) -> None:
    acquisition = json.loads(DATA_ACQUISITION.read_text(encoding="utf-8"))
    if acquisition.get("schema_version") != 1 or acquisition.get("network_default") != "deny":
        errors.append("evaluation-runner acquisition registry is unsafe or unsupported")
        return
    expected_sources = {
        "aqsoldb": ("8e02b548fd9a78778ff89a5aa9a460d1a289cc3a", "upstream_data_marked_cc0_1_0", "manual_pinned_upstream_acquisition"),
        "aqsoldbc_derivative": ("8e02b548fd9a78778ff89a5aa9a460d1a289cc3a", "derivative_lineage_package_pending", "user_supplied_local_package"),
        "complat": ("d4feda24b4bcb9efee9953605ba56af0e52dba4d", "no_repository_licence_identified", "user_supplied_local_package"),
        "tdc_dataset": ("c310c35f27e3f506411018ac43d97b8ba23ca652", "software_mit_dataset_rights_separate", "user_supplied_local_package"),
        "jchem_dataset": ("3da09dc96acde6c5c51d784307559067864ca779", "dataset_specific_review_pending", "user_supplied_local_package"),
        "chemberta_zinc_base_v1": ("761d6a18cf99db371e0b43baf3e2d21b3e865a20", "no_explicit_licence_in_retrieved_metadata", "identifier_only_no_bundled_weights"),
    }
    sources = {record.get("source_id"): record for record in acquisition.get("resources", [])}
    if set(sources) != set(expected_sources):
        errors.append("evaluation-runner acquisition source set mismatch")
    else:
        for source_id, expected in expected_sources.items():
            record = sources[source_id]
            observed = (record.get("revision"), record.get("licence_status"), record.get("acquisition_mode"))
            if observed != expected or record.get("automatic_download") is not False:
                errors.append(f"evaluation-runner acquisition contract mismatch: {source_id}")
    expected_source_map = {"R01": "aqsoldbc_derivative", "R02": "complat", "R03": "tdc_dataset", "R04": "tdc_dataset", "R05": "jchem_dataset", "R09": "complat"}
    if acquisition.get("evaluation_source_map") != expected_source_map:
        errors.append("evaluation-runner acquisition source mapping mismatch")
    parity = json.loads(EVALUATION_RUNNER_PARITY.read_text(encoding="utf-8"))
    if parity.get("status") != "PASS" or parity.get("gate") != "acquisition_data_layout_evaluation_runner_e1" or parity.get("model_identity") != "aug2_head4":
        errors.append("evaluation-runner parity status is not PASS")
    if (parity.get("row_level_inputs_redistributed"), parity.get("predictions_redistributed"), parity.get("scored_labels_redistributed")) != (False, False, False):
        errors.append("evaluation-runner parity manifest misstates redistribution")
    records = {record.get("evaluation_id"): record for record in parity.get("evaluations", [])}
    expected_rows = {key: value[1] for key, value in EXPECTED_EVALUATIONS.items()}
    expected_coefficients = {
        "R01": {"0": 0.5, "1": 0.5, "2": 0.5, "3": 0.5, "4": 0.5},
        "R02": {"0": 0.35783701629836606, "1": 0.34719288633809187, "2": 0.3483525332542907, "3": 0.35889311589834877, "4": 0.34989160615768977},
        "R03": {"0": 0.5107147095759091, "1": 0.5309883523177864, "2": 0.513853188782415, "3": 0.4749956727808701, "4": 0.5096218180594146},
        "R04": {"0": 0.5079547955184467},
        "R05": {"1": 0.5042305832703751, "2": 0.4575169080107138, "3": 0.5181060446991516, "4": 0.44616494504197796, "5": 0.5754599425836471},
        "R09": {"0": 0.3524569312559862},
    }
    if set(records) != set(expected_rows) or sum(record.get("rows", 0) for record in records.values()) != 38228:
        errors.append("evaluation-runner parity coverage or row total mismatch")
    else:
        for evaluation_id, expected_rows_value in expected_rows.items():
            record = records[evaluation_id]
            if record.get("rows") != expected_rows_value or record.get("coefficient_values") != expected_coefficients[evaluation_id]:
                errors.append(f"evaluation-runner coefficient or row parity mismatch: {evaluation_id}")
            if record.get("package_assembly_scored_labels_content_accessed") is not False:
                errors.append(f"evaluation-runner assembly accessed scored labels: {evaluation_id}")
            if record.get("maximum_descriptor_row_difference", float("inf")) > 2e-14 or record.get("maximum_neural_row_difference", float("inf")) > 2e-14 or record.get("maximum_dlg_sol_row_difference", float("inf")) > 2e-7:
                errors.append(f"evaluation-runner row-level parity mismatch: {evaluation_id}")
            if record.get("maximum_metric_absolute_difference") != 0.0 or record.get("maximum_bootstrap_absolute_difference") != 0.0:
                errors.append(f"evaluation-runner score parity mismatch: {evaluation_id}")
    if parity.get("all_assembly_phases_avoided_scored_label_content") is not True:
        errors.append("evaluation-runner label-access boundary is misstated")
    if parity.get("maximum_descriptor_row_difference", float("inf")) > 2e-14 or parity.get("maximum_neural_row_difference", float("inf")) > 2e-14 or parity.get("maximum_dlg_sol_row_difference", float("inf")) > 2e-7:
        errors.append("evaluation-runner aggregate prediction parity mismatch")
    if parity.get("maximum_metric_absolute_difference") != 0.0 or parity.get("maximum_bootstrap_absolute_difference") != 0.0:
        errors.append("evaluation-runner aggregate score parity mismatch")
    smoke = json.loads(EVALUATION_RUNNER_CLEAN_SMOKE.read_text(encoding="utf-8"))
    if smoke.get("status") != "PASS" or smoke.get("tests_discovered") != 81 or smoke.get("evaluation_runner_tests") != 16:
        errors.append("evaluation-runner clean-environment smoke test failed")
    if smoke.get("failures") != 0 or smoke.get("errors") != 0 or smoke.get("skipped") != 0:
        errors.append("evaluation-runner clean-environment tests were not clean")
    counterexample_keys = (
        "automatic_download_drift_rejected",
        "coefficient_parity_drift_rejected",
        "prediction_parity_drift_rejected",
        "label_access_drift_rejected",
        "evaluation_set_drift_rejected",
    )
    if smoke.get("validator_counterexamples") != 5 or any(smoke.get(key) is not True for key in counterexample_keys):
        errors.append("evaluation-runner validator counterexamples were not recorded")


def scan_public_text(errors: list[str]) -> None:
    for path in ROOT.rglob("*"):
        if (
            not path.is_file()
            or ".git" in path.parts
            or (
                path.name not in TEXT_DOTFILES
                and path.suffix.lower() not in TEXT_SUFFIXES
            )
        ):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        relative = path.relative_to(ROOT).as_posix()
        for label, pattern in FORBIDDEN_PATTERNS.items():
            if pattern.search(relative):
                errors.append(f"{label} in path: {relative}")
            if pattern.search(text):
                errors.append(f"{label}: {relative}")


def main() -> int:
    errors: list[str] = []
    validate_manifest(errors)
    validate_release_policy(errors)
    validate_tables(errors)
    validate_evaluation_registry(errors)
    validate_core_parity(errors)
    validate_descriptor_branch(errors)
    validate_training_orchestration(errors)
    validate_language_branch(errors)
    validate_geometry_branch(errors)
    validate_fusion_branch(errors)
    validate_dataset_adapters(errors)
    validate_evaluation_runner(errors)
    scan_public_text(errors)
    if errors:
        print("STAGING_VALIDATION=FAIL")
        for error in sorted(set(errors)):
            print(f"- {error}")
        return 1
    print("STAGING_VALIDATION=PASS")
    print("PUBLIC_RELEASE_READY=NO (v1.0 end-to-end reproducibility workflow and archival release remain pending)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
